### PR TITLE
Fix bug in interaction of scalar terms for row tables

### LINKED ISSUE #185: interaction of only continuous errors with one row
MWE:

``` julia
using StatsModels

a = rand(100)
b = rand(100)
y = rand(100)

d = (y=y, a=a, b=b)

f = apply_schema(@formula(y ~ a&b), schema(d))
# okay
modelcols(f.rhs, d)
# errors:
modelcols(f.rhs, (a=1., b=2.))
```

Result:

``` julia
ERROR: MethodError: no method matching vec(::Float64)
Closest candidates are:
  vec(::LinearAlgebra.Transpose{T,#s662} where #s662<:(AbstractArray{T,1} where T) where T) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/adjtrans.jl:201
  vec(::SparseArrays.AbstractSparseArray{Tv,Ti,1} where Ti where Tv) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/SparseArrays/src/sparsevector.jl:912
  vec(::FillArrays.Ones{T,N,Axes} where Axes where N) where T at /home/dave/.julia/packages/FillArrays/iArMw/src/fillalgebra.jl:3
  ...
Stacktrace:
 [1] kron_insideout(::Function, ::Float64, ::Vararg{Float64,N} where N) at /home/dave/.julia/packages/StatsModels/XQSUJ/src/terms.jl:506
 [2] modelcols at /home/dave/.julia/packages/StatsModels/XQSUJ/src/terms.jl:518 [inlined]
 [3] #36 at ./none:0 [inlined]
 [4] iterate at ./generator.jl:47 [inlined]
 [5] collect(::Base.Generator{Tuple{InteractionTerm{Tuple{ContinuousTerm{Float64},ContinuousTerm{Float64}}}},StatsModels.var"#36#37"{NamedTuple{(:a, :b),Tuple{Float64,Float64}}}}) at ./array.jl:665
 [6] modelcols(::MatrixTerm{Tuple{InteractionTerm{Tuple{ContinuousTerm{Float64},ContinuousTerm{Float64}}}}}, ::NamedTuple{(:a, :b),Tuple{Float64,Float64}}) at /home/dave/.julia/packages/StatsModels/XQSUJ/src/terms.jl:535
 [7] top-level scope at REPL[26]:2
```

The issue is that `kron_insideout` calls `vec` on a scalar when the inputs are
all scalars.

### PR DESCRIPTION
**Pull request by kleinschmidt**
Fixes #185

### CODE REVIEW

File: src/terms.jl [hunk 1]
```diff
@@ -508,7 +508,9 @@ reshape_last_to_i(i, a::AbstractMatrix) = reshape(a, size(a,1), ones(Int, i-1)..
 # table, some will be vectors, possibly some matrices
 function kron_insideout(op::Function, args...)
     args = (reshape_last_to_i(i,a) for (i,a) in enumerate(args))
-    vec(broadcast(op, args...))
+    out = broadcast(op, args...)
+    # flatten higher-dimensional output to vector
+    length(size(out)) > 1 ? vec(out) : out
```
Comment (nalimilan) [inline src/terms.jl:513]: Are we absolutely sure the result is going to be an array? This might be safer:
```suggestion
    out isa AbstractArray && ndims(out) > 1 ? vec(out) : out
```

Comment (kleinschmidt) [reply src/terms.jl:513]: The only situation I can think of (currently) is if a function term returns some non-array thing still survives the broadcasted `*` without an error and wouldn't cause a downstream error when `vcat`ed together with other vectors.

Comment (kleinschmidt) [reply src/terms.jl:513]: Actually, the `isa AbstractArray` check might be better overall, since the underlying problem was trying to call `vec` on things that were not `AbstractArray` (i.e. a scalar)

**Review by nalimilan — APPROVED** [review]
