### PR TITLE
fix boolean-as-categorical support

### LINKED ISSUE #326: Missing methods with v0.7.5 but not on 0.7.4
# v0.7.5

```julia
julia> using StatsModels

julia> data = (; x=[true, false], y=randn(2))
(x = Bool[1, 0], y = [0.6397358258449067, -1.1950505390298463])

julia> f = apply_schema(@formula(y ~ x), schema(data, Dict(:x => EffectsCoding())))
ERROR: MethodError: no method matching StatsModels.ContrastsMatrix(::Matrix{Float64}, ::BitVector, ::Vector{Bool}, ::EffectsCoding)
The type `StatsModels.ContrastsMatrix` exists, but no method is defined for this combination of argument types when trying to construct it.

Closest candidates are:
  StatsModels.ContrastsMatrix(::M, ::Vector{U}, ::Vector{T}, ::C) where {U, T, C<:AbstractContrasts, M<:(AbstractMatrix)}
   @ StatsModels ~/.julia/packages/StatsModels/kgR1k/src/contrasts.jl:110
  StatsModels.ContrastsMatrix(::StatsModels.FullDummyCoding, ::AbstractVector{T}) where T
   @ StatsModels ~/.julia/packages/StatsModels/kgR1k/src/contrasts.jl:285
  StatsModels.ContrastsMatrix(::C, ::AbstractVector) where C<:AbstractContrasts
   @ StatsModels ~/.julia/packages/StatsModels/kgR1k/src/contrasts.jl:160
  ...

Stacktrace:
  [1] StatsModels.ContrastsMatrix(contrasts::EffectsCoding, levels::Vector{Bool})
    @ StatsModels ~/.julia/packages/StatsModels/kgR1k/src/contrasts.jl:209
  [2] concrete_term(t::Term, xs::Vector{Bool}, contrasts::EffectsCoding)
    @ StatsModels ~/.julia/packages/StatsModels/kgR1k/src/schema.jl:214
  [3] concrete_term(t::Term, dt::@NamedTuple{x::Vector{Bool}, y::Vector{Float64}}, hints::Dict{Symbol, EffectsCoding})
    @ StatsModels ~/.julia/packages/StatsModels/kgR1k/src/schema.jl:186
  [4] (::StatsModels.var"#62#63"{@NamedTuple{x::Vector{Bool}, y::Vector{Float64}}, Dict{Symbol, EffectsCoding}})(t::Term)
    @ StatsModels ./none:0
  [5] iterate(::Base.Generator{Vector{Term}, StatsModels.var"#62#63"{@NamedTuple{…}, Dict{…}}})
    @ Base ./generator.jl:48
  [6] Dict{Term, AbstractTerm}(kv::Base.Generator{Vector{Term}, StatsModels.var"#62#63"{@NamedTuple{…}, Dict{…}}})
    @ Base ./dict.jl:93
  [7] Schema
    @ ~/.julia/packages/StatsModels/kgR1k/src/schema.jl:37 [inlined]
  [8] schema
    @ ~/.julia/packages/StatsModels/kgR1k/src/schema.jl:124 [inlined]
  [9] schema(dt::@NamedTuple{x::Vector{Bool}, y::Vector{Float64}}, hints::Dict{Symbol, EffectsCoding})
    @ StatsModels ~/.julia/packages/StatsModels/kgR1k/src/schema.jl:118
 [10] top-level scope
    @ REPL[19]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

# v0.7.4

```julia
julia> f = apply_schema(@formula(y ~ x), schema(data, Dict(:x => EffectsCoding())))
FormulaTerm
Response:
  y(continuous)
Predictors:
  x(EffectsCoding:2→1)
```

cc @nalimilan

### PR DESCRIPTION
**Pull request by palday**
fixes #326

### CODE REVIEW

File: src/contrasts.jl [hunk 1]
```diff
@@ -233,6 +233,12 @@ function StatsAPI.coefnames(C::AbstractContrasts, levels::AbstractVector, basein
     DataAPI.unwrap.(levels[not_base])
 end
 
+function StatsAPI.coefnames(C::AbstractContrasts, levels::AbstractVector{Bool}, baseind::Integer)
+    not_base = [1:(baseind-1); (baseind+1):length(levels)]
+    # broadcasted DataAPI.unwrap converts Vector{Bool} to BitVector
+    convert(Vector{Bool}, DataAPI.unwrap.(levels[not_base]))
```
[the remark this answers is not in the document]
Comment (palday) [reply src/contrasts.jl:239]: if this is your performance bottleneck ... 😂

File: src/contrasts.jl [hunk 2]
```diff
@@ -598,6 +604,10 @@ end
 StatsAPI.coefnames(C::HypothesisCoding, levels::AbstractVector, baseind::Int) =
     something(C.labels, DataAPI.unwrap.(levels[1:length(levels) .!= baseind]))
 
+# We need an explicit method for `AbstractVector{Bool}` to avoid an ambiguity
+StatsAPI.coefnames(C::HypothesisCoding, levels::AbstractVector{Bool}, baseind::Int) =
+    something(C.labels, DataAPI.unwrap.(levels[1:length(levels) .!= baseind]))
```
Comment (ararslan) [inline src/contrasts.jl:609]: I wonder whether it's worth using `invoke` to avoid duplicating the method body?
```suggestion
    invoke(coefnames, Tuple{HypothesisCoding,AbstractVector,Int}, C, levels, baseind)
```
Probably doesn't really matter.

**Review by ararslan — APPROVED** [review]

File: src/contrasts.jl (hunk 2 above)
Comment (palday) [reply src/contrasts.jl:609]: Hmmm, I'll consider that next time, going with the "no change" lazy and fast option for now 😂
